spring:
  cloud:
    stream:
      default-binder: local_solace
      bindings:
        input:
          destination: converter.processor
          group: WORKSHOP_USER
        outputSensor1:
          destination: WORKSHOP_USER/converter/processor/sensor1
        outputSensor2:
          destination: WORKSHOP_USER/converter/processor/sensor2
      binders:
        local_solace:
          type: solace
          environment:
            solace:
              java:
                host: 192.168.65.3
                msgVpn: default
                clientUsername: default
                clientPassword: default
                apiProperties:
                  generate_sequence_numbers: true
                  generate_sender_id: true
                  generate_send_timestamps: true
      solace:
        bindings:
          input:
            consumer:
              queueAdditionalSubscriptions: WORKSHOP_USER/converter/source
              autoBindDmq: true
logging:
  level:
    com.solacesystems.jcsmp: INFO
server:
  port: 0
