spring:
  cloud:
    stream:
      bindings:
        output:
          destination: WORKSHOP_USER/converter/source
          binder: solace
logging:
  level:
    com.solacesystems.jcsmp: INFO
server:
  port: 0
