spring:
  cloud:
    stream:
      default-binder: local_solace
      bindings:
        input:
          destination: [PROCESSOR_QUEUE_NAME]
          group: [STUDENT_ID]
        outputSensor1:
          destination: [STUDENT_ID]/[PROCESSOR_SENSOR1_TOPIC]
        outputSensor2:
          destination: [STUDENT_ID]/[PROCESSOR_SENSOR2_TOPIC]
      binders:
        local_solace:
          type: solace
          environment:
            solace:
              java:
                host: [IP_ADDRESS]
                msgVpn: [VPN_NAME]
                clientUsername: [CLIENT_USERNAME]
                clientPassword: [CLIENT_PASSWORD]
                # Add API properties here
      solace:
        bindings:
          input:
            consumer:
              queueAdditionalSubscriptions: [STUDENT_ID]/[PROCESSOR_SUBSCRIPTION]
              # Add DMQ configuration here
logging:
  level:
    com.solacesystems.jcsmp: INFO
server:
  port: 0
