spring:
  cloud:
    stream:
      bindings:
        output:
          destination: [STUDENT_ID]/[SOURCE_TOPIC]
          binder: solace
logging:
  level:
    com.solacesystems.jcsmp: INFO
server:
  port: 0
