spring:
  cloud:
    stream:
      bindings:
        input:
          destination: converter.sink
          binder: local_solace
          group: WORKSHOP_USER
      binders:
        local_solace:
          type: solace
          environment:
            solace:
              java:
                host: 192.168.65.3
                msgVpn: default
                clientUsername: default
                clientPassword: default
      solace:
        bindings:
          input:
            consumer:
              queueAdditionalSubscriptions: WORKSHOP_USER/converter/processor/>
logging:
  level:
    com.solacesystems.jcsmp: INFO
server:
  port: 0
